#!/usr/bin/env ts-node

/**
 * Generate TypeScript types from OpenAPI specification
 *
 * This script generates TypeScript types from the OpenAPI spec for the relayer service.
 * The generated types can be used by external integrators (e.g., wallet teams) to ensure
 * type safety when calling the relayer API.
 *
 * Usage:
 *   npm run generate:openapi-types
 *   yarn generate:openapi-types
 *   pnpm generate:openapi-types
 *
 * Requirements:
 *   - openapi-typescript: npm package for generating TypeScript types from OpenAPI specs
 *
 * Install dependencies if needed:
 *   npm install -D openapi-typescript
 */

import { writeFileSync } from 'fs';
import { join } from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

// ESM equivalent of __dirname
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const OPENAPI_SPEC_PATH = join(__dirname, '../services/relayer/openapi.yaml');
const OUTPUT_PATH = join(__dirname, '../services/relayer/src/api/openapi-types.ts');

/**
 * Generate TypeScript types from OpenAPI specification
 */
async function generateTypes() {
  try {
    // Dynamic import to avoid requiring openapi-typescript at build time if not present
    const { default: openapiTS } = await import('openapi-typescript');

    console.log(`Generating TypeScript types from ${OPENAPI_SPEC_PATH}...`);

    const schema = await openapiTS(OPENAPI_SPEC_PATH, {
      // Use the version from the OpenAPI spec
      version: '3.1',
      // Export as default
      exportType: false,
      // Add a comment at the top of the generated file
      commentHeader: `/**
 * Auto-generated TypeScript types from OpenAPI specification
 *
 * This file is automatically generated from services/relayer/openapi.yaml
 * Regenerate by running: npm run generate:openapi-types
 *
 * DO NOT EDIT THIS FILE MANUALLY - your changes will be overwritten
 */
`,
    });

    writeFileSync(OUTPUT_PATH, schema);
    console.log(`✓ Successfully generated types to ${OUTPUT_PATH}`);
  } catch (error) {
    if ((error as any).code === 'MODULE_NOT_FOUND') {
      console.error('Error: openapi-typescript is not installed.');
      console.error('Install it with: npm install -D openapi-typescript');
      process.exit(1);
    }
    console.error('Error generating types:', error);
    process.exit(1);
  }
}

// Run the generator
generateTypes().catch((error) => {
  console.error('Fatal error:', error);
  process.exit(1);
});
